const SET_QUEST = 'SET_QUEST'
const ADD_QUEST = 'ADD_QUEST'
const DEL_QUEST = 'DEL_QUEST'
const EDIT_QUEST = 'EDIT_QUEST'
const SET_ANSW = 'SET_ANSW'
const RIGHT_ANSWER = 'RIGHT_ANSWER'
const SET_QUEST_SAGA = 'SET_QUEST_SAGA'
const ADD_QUEST_SAGA = 'ADD_QUEST_SAGA'
const SET_USER_QUEST = 'SET_USER_QUEST'


export {
  SET_QUEST,
  ADD_QUEST,
  DEL_QUEST,
  EDIT_QUEST,
  SET_ANSW,
  RIGHT_ANSWER,
  SET_QUEST_SAGA,
  ADD_QUEST_SAGA,
  SET_USER_QUEST,
}
